controllers/api_routes_measurement.py
from flask import Blueprint, request, jsonify
from services.measurement_service import (
    insert_measurement,
    get_last_measurement,
    get_last_x_measurements,
    delete_measurement_by_id,
    serialize_measurement
)

measurement_blueprint = Blueprint('measurement', __name__)

@measurement_blueprint.route('/measurements', methods=['POST'])
def add_measurement():
    data = request.get_json()
    success = insert_measurement(data)
    return jsonify(success=success), 201 if success else 400

@measurement_blueprint.route('/measurements/latest', methods=['GET'])
def latest_measurement():
    measurement = get_last_measurement()
    if measurement:
        return jsonify(serialize_measurement(measurement)), 200
    else:
        return jsonify({"message": "No measurements found"}), 404

@measurement_blueprint.route('/measurements/last/<int:x>', methods=['GET'])
def last_x_measurements(x):
    measurements = get_last_x_measurements(x)
    serialized_measurements = [serialize_measurement(m) for m in measurements]
    return jsonify(serialized_measurements), 200 if measurements else 404

@measurement_blueprint.route('/measurements/delete/<int:id>', methods=['DELETE'])
def delete_measurement(id):
    success = delete_measurement_by_id(id)
    return jsonify(success=success), 200 if success else 400

controllers/api_routes_user.py
from flask import Blueprint, request, redirect, url_for, render_template,session
from services.user_service import login_user, register_user

auth_blueprint = Blueprint('auth', __name__)

@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    error_message = None
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        if login_user(username, password):
           return redirect(url_for('site.dashboard'))
        error_message = "Invalid username or password."
    return render_template('login.html',error_message=error_message)


@auth_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    error_message = None
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        confirm_password = request.form['confirm_password']

        if password != confirm_password:
            error_message = "Passwords do not match."
        elif not register_user(username, email, password):
            error_message = "User with this username or email already exists."
        else:
            return redirect(url_for('auth.login'))
    return render_template('register.html', error_message=error_message)

@auth_blueprint.route('/logout')
def logout():
    session.clear()  # Clear the session
    return redirect(url_for('site.index'))

controllers/site_routes.py
# site_routes.py
from flask import Blueprint, render_template, session
from services.measurement_service import (
    get_last_measurement,
    get_last_x_measurements,
)

site_blueprint = Blueprint('site', __name__)

@site_blueprint.route('/')
def index():
    return render_template('login.html')

@site_blueprint.route('/dashboard')
def dashboard():
    latest_measurement = get_last_measurement()
    last_measurements = get_last_x_measurements(5)  # For example, get the last 5
    num_last_measurements = len(last_measurements)
    username = session.get("username", "Unknown User")

    return render_template(
        'dashboard.html',
        latest_measurement=latest_measurement,
        last_measurements=last_measurements,
        num_last_measurements=num_last_measurements,
        username=username
    )

main.py
from flask import Flask
from database.database import db
from controllers.site_routes import site_blueprint
from controllers.api_routes_user import auth_blueprint
from controllers.api_routes_measurement import measurement_blueprint

app = Flask(__name__)
app.config['SECRET_KEY'] = 'supersecretkey'  # Set your secret key here
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///weather_app.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

with app.app_context():
    db.create_all()


# Register the API blueprint
app.register_blueprint(auth_blueprint, url_prefix='/auth')
app.register_blueprint(measurement_blueprint, url_prefix='/api')
app.register_blueprint(site_blueprint)

if __name__ == '__main__':
    app.run(debug=True)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="navbar-center mx-auto">
                <a class="navbar-brand" href="{{ url_for('site.dashboard') }}">Temperature Tracker</a>
            </div>
            <div class="form-inline">
                {% if username %}
                <span class="navbar-text mr-3">{{ username }}</span>
                <button class="btn btn-outline-primary" onclick="window.location.href='{{ url_for('auth.logout') }}';">Logout</button>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<!-- Latest Measurement Display -->
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Latest Measurement</h5>
    <p class="card-text" id="latest-measurement">
      <!-- Latest measurement will be filled by JavaScript -->
    </p>
  </div>
</div>

<!-- Input for Number of Latest Records to Show -->
<div class="mb-3">
  <form id="numRecordsForm">
    <div class="form-group">
      <label for="numRecords">Enter Number of Latest Records to Show:</label>
      <input type="number" class="form-control" id="numRecords" name="numRecords" min="1">
      <button type="submit" class="btn btn-primary mt-2">Update</button>
    </div>
  </form>
</div>

<!-- Table of Last X Measurements with Deletion Icon -->
<div class="table-responsive">
  <table class="table" id="measurements-table">
    <thead>
      <tr>
        <th scope="col">Timestamp</th>
        <th scope="col">Temperature (°C)</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <!-- Measurements will be filled by JavaScript -->
    </tbody>
  </table>
</div>

<!-- Input for New Measurement -->
<div class="mb-3">
  <form id="addMeasurementForm">
    <div class="form-group">
      <label for="newTemp">New Temperature (°C):</label>
      <input type="number" step="0.1" class="form-control" id="newTemp" placeholder="Enter temperature (e.g., 1.5)">
      <button type="submit" class="btn btn-primary mt-2">Add Measurement</button>
    </div>
  </form>
</div>


<!-- Rest of your existing content -->


<!-- Placeholder for Chart -->
<div id="temperatureChart" class="mt-4">
  <!-- The chart will be injected here by a JavaScript charting library like Chart.js -->
  <canvas></canvas>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Function to update the latest measurement display
    function updateLatestMeasurement() {
        fetch('/api/measurements/latest')
            .then(response => response.json())
            .then(data => {
                const measurementDiv = document.getElementById('latest-measurement');
                if (data.message) {
                    measurementDiv.innerHTML = 'No measurements available';
                } else {
                    measurementDiv.innerHTML = `
                        Timestamp: ${data.timestamp}<br>
                        Temperature: ${data.temperature}°C
                    `;
                }
            });
    }

    // Function to update the table with the last X measurements
    function updateMeasurementsTable(numRecords) {
        fetch(`/api/measurements/last/${numRecords}`)
            .then(response => response.json())
            .then(data => {
                const tableBody = document.querySelector('#measurements-table tbody');
                tableBody.innerHTML = data.map(measurement => `
                    <tr>
                        <td>${measurement.timestamp}</td>
                        <td>${measurement.temperature}</td>
                        <td><button class="btn btn-danger delete-record" data-id="${measurement.id}">X</button></td>
                    </tr>
                `).join('');
            });
    }

    // Fetch and display the latest measurement when the page loads
    updateLatestMeasurement();
    updateMeasurementsTable(5);  // Initialize with the latest 5 measurements

    // Event listener for the form to update the table
    const form = document.getElementById('numRecordsForm');
    form.addEventListener('submit', function(event) {
        event.preventDefault();
        const numRecords = document.getElementById('numRecords').value;
        updateMeasurementsTable(numRecords);
    });

    // Event listener for the form to add a new measurement
    const addForm = document.getElementById('addMeasurementForm');
    addForm.addEventListener('submit', function(event) {
        event.preventDefault();
        const temp = document.getElementById('newTemp').value;
        fetch('/api/measurements', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ "temp": parseFloat(temp) })
        }).then(response => {
            if (response.ok) {
                updateLatestMeasurement();
                updateMeasurementsTable(document.getElementById('numRecords').value || 5);
            }
        });
    });

    // Event delegation for deleting measurements
    const tableBody = document.querySelector('#measurements-table tbody');
    tableBody.addEventListener('click', function(event) {
        if (event.target.classList.contains('delete-record')) {
            event.preventDefault();
            const id = event.target.getAttribute('data-id');
            fetch(`/api/measurements/delete/${id}`, { method: 'DELETE' })
                .then(response => {
                    if (response.ok) {
                        updateMeasurementsTable(document.getElementById('numRecords').value || 5);
                        updateLatestMeasurement();
                    } else {
                        console.error(`Failed to delete measurement with id ${id}`);
                    }
                })
                .catch(error => console.error('Error during delete:', error));
        }
    });
});
</script>
{% endblock %}

templates/login.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <title>Login - Temperature Tracker</title>
</head>

<body>
  <div class="container h-100">
    <div class="row justify-content-center align-items-center" style="height:100vh;">
      <div class="col-4">
        <div class="card">
          <article class="card-body">
            <h4 class="card-title text-center mb-4 mt-1">Sign in</h4>
            <hr>
            <form method="POST" action="{{ url_for('auth.login') }}">
              <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" required>
              </div>
              <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" required>
              </div>
              <!-- Display error message here -->
              {% if error_message %}
              <div class="alert alert-danger" role="alert">{{ error_message }}</div>
              {% endif %}
              <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Login</button>
              </div>
            </form>
          </article>
        </div>
        <p class="text-center mt-4">Don't have an account? <a href="{{ url_for('auth.register') }}">Register</a></p>
      </div>
    </div>
  </div>
</body>

</html>

templates/register.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <title>Register - Temperature Tracker</title>
</head>

<body>
  <div class="container h-100">
    <div class="row justify-content-center align-items-center" style="height:100vh;">
      <div class="col-4">
        <div class="card">
          <article class="card-body">
            <h4 class="card-title text-center mb-4 mt-1">Register</h4>
            <hr>
            <form method="POST" action="{{ url_for('auth.register') }}">
              <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" required>
              </div>
              <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" required>
              </div>
              <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" required>
              </div>
              <div class="form-group">
                <label for="confirm_password">Confirm Password</label>
                <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
              </div>
              <!-- Display error message here -->
              {% if error_message %}
              <div class="alert alert-danger" role="alert">{{ error_message }}</div>
              {% endif %}
              <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Register</button>
              </div>
            </form>
          </article>
        </div>
        <p class="text-center mt-4">Already have an account? <a href="{{ url_for('auth.login') }}">Login</a></p>
      </div>
    </div>
  </div>
</body>

</html>